-- V2 Bootstrap schema (idempotent)
-- Works on:
--  - fresh empty DB: creates tables/constraints/indexes
--  - existing DB: no-ops when objects already exist

-- NOTE: Do NOT create flyway_schema_history here. Flyway manages it.

-- USERS
CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT user_pkey PRIMARY KEY (id)
    );

-- BANK ACCOUNT
CREATE TABLE IF NOT EXISTS bank_account_model
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    user_id INTEGER                                 NOT NULL,
    CONSTRAINT bank_account_model_pkey PRIMARY KEY (id)
    );

-- BUCKET
CREATE TABLE IF NOT EXISTS bucket_model
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    user_id INTEGER                                 NOT NULL,
    CONSTRAINT bucket_model_pkey PRIMARY KEY (id)
    );

-- TRANSACTION
CREATE TABLE IF NOT EXISTS transaction_model
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount            NUMERIC(12, 2)                          NOT NULL,
    date              DATE                                    NOT NULL,
    description       VARCHAR(255)                            NOT NULL,
    income_or_expense VARCHAR(255)                            NOT NULL,
    bank_account_id   BIGINT                                  NOT NULL,
    bucket_id         BIGINT                                  NOT NULL,
    user_id           INTEGER                                 NOT NULL,
    CONSTRAINT transaction_model_pkey PRIMARY KEY (id)
    );

-- UNIQUE constraint (only if missing)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_tx_user_date_amount_desc'
    ) THEN
ALTER TABLE transaction_model
    ADD CONSTRAINT uk_tx_user_date_amount_desc
        UNIQUE (user_id, date, amount, description);
END IF;
END $$;

-- Index (safe)
CREATE INDEX IF NOT EXISTS idx_tx_user_date
    ON transaction_model (user_id, date);

-- Foreign keys (only if missing)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bank_account_user') THEN
ALTER TABLE bank_account_model
    ADD CONSTRAINT fk_bank_account_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;
END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bucket_user') THEN
ALTER TABLE bucket_model
    ADD CONSTRAINT fk_bucket_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;
END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transaction_bank_account') THEN
ALTER TABLE transaction_model
    ADD CONSTRAINT fk_transaction_bank_account
        FOREIGN KEY (bank_account_id) REFERENCES bank_account_model (id) ON DELETE NO ACTION;
END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transaction_bucket') THEN
ALTER TABLE transaction_model
    ADD CONSTRAINT fk_transaction_bucket
        FOREIGN KEY (bucket_id) REFERENCES bucket_model (id) ON DELETE NO ACTION;
END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transaction_user') THEN
ALTER TABLE transaction_model
    ADD CONSTRAINT fk_transaction_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;
END IF;
END $$;
