-- V__alter_users_id_and_constraints.sql

ALTER TABLE users
    ALTER COLUMN id TYPE BIGINT;

ALTER TABLE users
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE users
    ALTER COLUMN username SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT uk_users_username UNIQUE (username);
